default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: notes_app_development

test:
  <<: *default
  database: notes_app_test

production:
  adapter: postgresql
  encoding: unicode
  database: notes_app_production
  username: rails
  password: password
  host: localhost